

#define DINO_POSTION_X 20
#define DINO_POSTION_Y 500
#define DINO_POSTION_W 200
#define DINO_POSTION_H 200
#define DINO_COLLISION_X 60
#define DINO_COLLISION_Y 540
#define DINO_COLLISION_W 100
#define DINO_COLLISION_H 150